Repository afup/web, pull requests merged in 2025-06, with the labels that each got.

#1823 Installation de PHPStan en dépendance de dev
  .github/workflows/ci.yml
  Makefile
  composer.json
  composer.lock
  phpstan.neon
Labels: type:tech

#1822 Refactor du DTO en readonly
  htdocs/pages/administration/forum_inscriptions.php
  sources/AppBundle/Controller/Admin/Event/StatsAction.php
  sources/AppBundle/Controller/Admin/HomeAction.php
  sources/AppBundle/Event/Model/EventStats.php
  sources/AppBundle/Event/Model/EventStats/DailyStats.php
  sources/AppBundle/Event/Model/EventStats/TicketTypeStats.php
  sources/AppBundle/Event/Model/Repository/EventStatsRepository.php
  sources/AppBundle/Slack/MessageFactory.php
Labels: type:tech

#1824 Refactor des annotations en attributes
  app/config/config.yml
  composer.json
  composer.lock
  sources/AppBundle/Association/Form/UserEditFormData.php
  sources/AppBundle/Association/Model/User.php
  sources/AppBundle/Controller/Admin/Event/PricesAddAction.php
  sources/AppBundle/Event/Form/GithubUserType.php
  sources/AppBundle/Event/Model/Invoice.php
  sources/AppBundle/Event/Model/Ticket.php
  sources/AppBundle/Event/Validator/Constraints/AvailableTicket.php
  sources/AppBundle/Event/Validator/Constraints/CorporateMember.php
  sources/AppBundle/Event/Validator/Constraints/EarlyBirdTicket.php
  sources/AppBundle/Event/Validator/Constraints/EarlyBirdTicketValidator.php
  sources/AppBundle/Event/Validator/Constraints/LoggedInMember.php
  sources/AppBundle/Event/Validator/Constraints/PublicTicket.php
  sources/AppBundle/Event/Validator/Constraints/TicketsCfpSubmitter.php
  sources/AppBundle/Validator/Constraints/UniqueEntity.php
Labels: type:tech

#1825 Utilisation du bundle Valinor
  app/config/bundles.php
  composer.json
  composer.lock
  sources/AppBundle/Controller/Admin/TechLetter/TechLetterGenerateController.php
  sources/AppBundle/Indexation/Meetups/MeetupClient.php
  sources/AppBundle/SocialNetwork/Bluesky/BlueskyTransport.php
  sources/AppBundle/TechLetter/Model/TechLetterFactory.php
  tests/unit/AppBundle/Indexation/Meetups/MeetupClientTest.php
  tests/unit/AppBundle/TechLetter/Model/TechLetterFactoryTest.php
Labels: type:tech

#1839 Mise à jour de robmorgan/phinx
  composer.json
  composer.lock
  db/migrations/20230504231444_afup_meetup.php
Labels: type:tech

#1852 Modernisation du typage
  composer.json
  composer.lock
  sources/AppBundle/Controller/Event/CFP/EditAction.php
  sources/AppBundle/Controller/Event/EventActionHelper.php
Labels: type:tech

#1850 Séparation des actions de TechLetter dans plusieurs classes
  app/config/routing/techletter_admin.yml
  app/config/services.yml
  sources/AppBundle/Controller/Admin/TechLetter/GenerateAction.php
  sources/AppBundle/Controller/Admin/TechLetter/HistoryAction.php
  sources/AppBundle/Controller/Admin/TechLetter/IndexAction.php
  sources/AppBundle/Controller/Admin/TechLetter/MembersAction.php
  sources/AppBundle/Controller/Admin/TechLetter/PreviewAction.php
  sources/AppBundle/Controller/Admin/TechLetter/RetrieveDataAction.php
  sources/AppBundle/Controller/Admin/TechLetter/SendTestAction.php
  sources/AppBundle/Controller/Admin/TechLetter/TechLetterGenerateController.php
Labels: type:tech

#1857 Renommage du controller CMS en action pour harmoniser
  app/config/routing/cms_page.yml
  sources/AppBundle/Controller/Website/Cms/DisplayAction.php
Labels: type:tech

#1860 Refactor des controllers CompanyPublicProfile pour harmoniser
  app/config/routing.yml
  app/config/services.yml
  sources/AppBundle/Controller/Website/CompanyPublicProfile/CompanyPublicProfileController.php
  sources/AppBundle/Controller/Website/CompanyPublicProfile/IndexAction.php
  sources/AppBundle/Controller/Website/CompanyPublicProfile/ListAction.php
  sources/AppBundle/Controller/Website/CompanyPublicProfile/LogoAction.php
  sources/AppBundle/Controller/Website/Member/CompanyPublicProfileController.php
Labels: type:tech

#1856 Séparation des actions Vote dans plusieurs classes
  app/config/routing/event.yml
  sources/AppBundle/Controller/Event/Vote/IndexAction.php
  sources/AppBundle/Controller/Event/Vote/NewAction.php
  sources/AppBundle/Controller/Event/Vote/VoteController.php
Labels: type:tech

#1854 Déplacement des controllers SponsorScan dans un namespace dédié
  app/config/routing/event.yml
  sources/AppBundle/Controller/Event/SponsorScan/DeleteAction.php
  sources/AppBundle/Controller/Event/SponsorScan/ExportAction.php
  sources/AppBundle/Controller/Event/SponsorScan/FlashAction.php
  sources/AppBundle/Controller/Event/SponsorScan/IndexAction.php
  sources/AppBundle/Controller/Event/SponsorScan/NewAction.php
  sources/AppBundle/Controller/Event/SponsorScan/SponsorScanController.php
  sources/AppBundle/Controller/Event/SponsorScanController.php
Labels: type:tech

#1864 Refactor des controllers News pour harmoniser
  app/config/routing/news.yml
  app/config/services.yml
  sources/AppBundle/Controller/Website/News/DisplayAction.php
  sources/AppBundle/Controller/Website/News/ListAction.php
  sources/AppBundle/Subscriber/SitemapXmlSubscriber.php
Labels: type:tech

#1855 Déplacement des controllers Speaker dans un namespace dédié
  app/config/routing/event.yml
  sources/AppBundle/Controller/Event/Speaker/FilesAction.php
  sources/AppBundle/Controller/Event/Speaker/PageAction.php
  sources/AppBundle/Controller/Event/Speaker/SuggestionAction.php
Labels: type:tech

#1859 Renommage des controllers Member en actions pour harmoniser
  app/config/routing/member.yml
  sources/AppBundle/Controller/Website/Member/CompanyAction.php
  sources/AppBundle/Controller/Website/Member/CompanyPublicProfileAction.php
  sources/AppBundle/Controller/Website/Member/IndexAction.php
  sources/AppBundle/Controller/Website/Member/MembersAction.php
Labels: type:tech

#1861 Refactor des controllers Global pour harmoniser
  app/config/routing/global.yml
  app/config/services.yml
  sources/AppBundle/Controller/Website/Global/HomeAction.php
  sources/AppBundle/Controller/Website/Global/HtmlSitemapAction.php
Labels: type:tech

#1863 Uniformisation de l'instanciation du service Cotisations
  app/config/services.yml
  sources/Afup/Association/CotisationsFactory.php
  sources/AppBundle/Association/CompanyMembership/SubscriptionManagement.php
  sources/AppBundle/Controller/Website/MemberShipController.php
Labels: type:tech

#1865 Correction du nom du controller
  app/config/routing/meetups.yml
Labels: type: bug

#1874 Utilisation de l'année en cours comme valeur par défaut
  htdocs/pages/administration/forum_sessions.php
Labels: type: enhancement

#1870 Refactor des controllers Github pour harmoniser
  app/config/routing/connection.yml
  sources/AppBundle/Controller/Github/ConnectAction.php
  sources/AppBundle/Controller/Github/ConnectCheckAction.php
  sources/AppBundle/Controller/GithubController.php
Labels: type:tech

#1867 Refactor des controllers Techno Watch pour harmoniser
  app/config/routing/techletter.yml
  app/config/services.yml
  sources/AppBundle/Controller/Website/TechnoWatch/CalendarAction.php
Labels: type:tech

#1876 Mise à jour de `cuyz/valinor` en v2
  composer.json
  composer.lock
Labels: type:tech

#1879 Nettoyage du controller MemberShip
  app/config/services.yml
  sources/Afup/Droits.php
  sources/AppBundle/Controller/Website/MemberShipController.php
Labels: type:tech

#1877 Refactor des controllers Ticket pour harmoniser
  app/config/routing/event.yml
  sources/AppBundle/Controller/Event/Ticket/PayboxCallbackAction.php
  sources/AppBundle/Controller/Event/Ticket/PayboxRedirectAction.php
  sources/AppBundle/Controller/Event/Ticket/PaymentAction.php
  sources/AppBundle/Controller/Event/Ticket/SponsorTicketAction.php
  sources/AppBundle/Controller/Event/Ticket/SponsorTicketFormAction.php
  sources/AppBundle/Controller/Event/Ticket/TicketAction.php
  sources/AppBundle/Controller/Event/TicketController.php
Labels: type:tech

#1878 Refactor des controllers Event pour harmoniser
  app/config/routing/event.yml
  sources/AppBundle/Controller/Event/Event/CalendarAction.php
  sources/AppBundle/Controller/Event/Event/CalendarLatestAction.php
  sources/AppBundle/Controller/Event/Event/IndexAction.php
  sources/AppBundle/Controller/Event/Event/OpenFeedbackJsonAction.php
  sources/AppBundle/Controller/Event/Event/PlanningIcsAction.php
  sources/AppBundle/Controller/Event/Event/PlanningJsonAction.php
  sources/AppBundle/Controller/Event/Event/ShowAction.php
  sources/AppBundle/Controller/Event/Event/SpeakerInfosIndexAction.php
  sources/AppBundle/Controller/Event/EventController.php
Labels: type:tech
