Repository afup/web, pull requests merged in 2025-03, with the labels that each got.

#1654 Mise à jour de presta/sitemap-bundle
  app/config/routing.yml
  composer.json
  composer.lock
  sources/AppBundle/Subscriber/SitemapXmlSubscriber.php
  tests/behat/features/PublicSite/Sitemaps.feature
Labels: type:tech

#1657 Correction de dépréciations
  app/AppKernel.php
  app/config/config.yml
  app/config/config_dev.yml
  app/config/security.yml
  app/config/services.yml
  bin/console
  htdocs/app.php
  htdocs/robots/planete/explorateur.php
  sources/AppBundle/Association/Form/HelpMessageExtension.php
  sources/AppBundle/Command/UpdateMailchimpMembersCommand.php
  sources/AppBundle/Event/Form/SpeakerSuggestionType.php
  sources/AppBundle/Event/Form/TicketSpecialPriceType.php
  sources/AppBundle/GeneralMeeting/PrepareFormType.php
  sources/AppBundle/Twig/AssetsExtension.php
  templates/admin/speaker/edit.html.twig
  templates/site/company_membership/adhesion_entreprise.html.twig
  translations/messages.en.yml
  translations/messages.fr.yml
  translations/validators.fr.yml
Labels: type:tech

#1660 Désactivation des logs des erreurs 404
  app/config/config_prod.yml
Labels: priority: low, type:tech

#1661 Correction de dépréciations
  app/config/routing_dev.yml
  sources/AppBundle/Association/CompanyMembership/InvitationMail.php
  sources/AppBundle/Controller/Event/CFP/EditAction.php
  sources/AppBundle/Controller/Event/CFP/InviteAction.php
  sources/AppBundle/Controller/Event/CFP/ProposeAction.php
  sources/AppBundle/Controller/Event/CFP/SpeakerAction.php
  sources/AppBundle/Controller/Legacy/Forum2016SessionsAction.php
  sources/AppBundle/Event/Sponsorship/SponsorshipLeadMail.php
  sources/AppBundle/Event/Talk/InvitationFormHandler.php
  sources/AppBundle/Event/Ticket/SponsorTokenMail.php
  sources/AppBundle/Listener/LocaleEventSubscriber.php
  sources/AppBundle/Slack/MessageFactory.php
  sources/AppBundle/SpeakerInfos/Form/HotelReservationType.php
  tests/units/AppBundle/Notifier/SlackNotifier.php
Labels: type:tech

#1662 Mise à jour de packages en prévision de SF 5.4
  behat.yml
  composer.json
  composer.lock
  db/migrations/20200709202035_remove_pmr.php
  sources/AppBundle/Email/Mailer/Adapter/PhpMailerAdapter.php
Labels: type:tech

#1658 Installation de composer via Docker
  Makefile
  clevercloud/scripts/change_composer_version.sh
  docker/dockerfiles/apachephp/Dockerfile
Labels: type:tech

#1664 Correction des types de l'entité `Talk`
  htdocs/pages/administration/forum_sessions.php
  sources/AppBundle/Event/Model/Talk.php
Labels: type:tech

#1665 Correction d'annotations pour PHPStan niveau 3
  sources/AppBundle/Event/Model/Repository/PlanningRepository.php
  sources/AppBundle/Indexation/Meetups/Runner.php
  sources/AppBundle/Indexation/Meetups/Transformer.php
  sources/AppBundle/Indexation/Talks/Runner.php
Labels: type:tech

#1666 Suppression de l'import depuis la Caisse d'Épargne
  htdocs/pages/administration/compta_journal.php
  sources/AppBundle/Compta/Importer/CaisseEpargne.php
  sources/AppBundle/Compta/Importer/CreditMutuel.php
  sources/AppBundle/Compta/Importer/Factory.php
  sources/AppBundle/Compta/Importer/Importer.php
Labels: type: enhancement

#1667 Corrections PHPStan niveau 3
  sources/Afup/Bootstrap/Http.php
  sources/AppBundle/Association/Model/CompanyMember.php
  sources/AppBundle/Association/Model/GeneralMeetingQuestion.php
  sources/AppBundle/Association/Model/User.php
  sources/AppBundle/Controller/Admin/Event/RoomAction.php
  sources/AppBundle/Event/Model/Planning.php
  sources/AppBundle/Event/Model/Repository/SponsorScanRepository.php
  sources/AppBundle/Event/Model/Speaker.php
  sources/AppBundle/Event/Model/SponsorScan.php
Labels: type:tech

#1670 Correction de quelques erreurs
  sources/AppBundle/Association/Model/CompanyMember.php
  sources/AppBundle/Controller/Website/StaticController.php
  tests/behat/files/super_apero.csv
Labels: type: bug, priority: high

#1672 Gestion du null
  sources/AppBundle/Event/Model/Talk.php
Labels: type: bug

#1669 Préparation pour mise à jour Symfony 5.4
  app/config/routing/admin_event.yml
  app/config/routing/admin_site.yml
  htdocs/pages/administration/forum_sessions.php
  htdocs/templates/administration/compta_devis.html
  htdocs/templates/administration/compta_facture.html
  htdocs/templates/administration/forum_facturation.html
  htdocs/templates/administration/forum_inscriptions.html
  htdocs/templates/administration/forum_sessions.html
  htdocs/templates/administration/personnes_morales.html
  htdocs/templates/administration/site_articles.html
  htdocs/templates/administration/site_feuilles.html
  sources/Afup/Bootstrap/_Common.php
  sources/Afup/Utils/SymfonyKernel.php
  sources/AppBundle/Controller/Admin/VoteController.php
  sources/AppBundle/Controller/Event/TicketController.php
  sources/AppBundle/Controller/Website/Member/CompanyPublicProfileController.php
  sources/AppBundle/Controller/Website/MemberShipController.php
  sources/AppBundle/Event/JsonLd.php
Labels: type:tech

#1673 Mise à jour des meetup existants
  sources/AppBundle/Association/Model/Repository/UserRepository.php
  sources/AppBundle/Command/ScrappingMeetupEventsCommand.php
  sources/AppBundle/Event/Model/Repository/MeetupRepository.php
Labels: type: enhancement

#1679 Correction de la création de cotisation
  sources/Afup/Association/Cotisations.php
Labels: type: bug, priority: high

#1575 feat(events): add a selector for easier event comparison
  sources/AppBundle/Controller/Admin/Event/StatsAction.php
  sources/AppBundle/Event/Form/EventCompareSelectType.php
  sources/AppBundle/Event/Model/Repository/EventRepository.php
  templates/admin/event/compare_event.html.twig
  templates/admin/event/stats.html.twig
Labels: type: enhancement

#1675 Remplacement de Guzzle par le client HTTP de Symfony
  app/config/config.yml
  app/config/packages/http_client.yaml
  app/config/services.yml
  composer.json
  composer.lock
  sources/AppBundle/Command/DevCallBackPayboxCotisationCommand.php
  sources/AppBundle/Github/GithubClient.php
  sources/AppBundle/Indexation/Meetups/MeetupClient.php
  sources/AppBundle/Notifier/SlackNotifier.php
  tests/unit/AppBundle/Indexation/Meetups/MeetupClientTest.php
  tests/unit/AppBundle/Notifier/SlackNotifierTest.php
Labels: priority: low, type:tech

#1684 Ajout de la dépendance symfony/http-client
  composer.json
  composer.lock
Labels: type:tech

#1686 Ajout de la dépendance `symfony/lock`
  composer.json
  composer.lock
Labels: type: bug

#1687 Ajout de la dépendance `symfony/mime`
  composer.json
  composer.lock
Labels: type: bug

#1677 Migration vers symfony de la partie événement de l'admin
  .gitignore
  app/config/config.yml
  app/config/routing/admin_event.yml
  app/config/services.yml
  htdocs/pages/administration/forum_gestion.php
  htdocs/templates/administration/forum_gestion.html
  sources/AppBundle/Controller/Admin/Event/EventAction.php
  sources/AppBundle/Controller/Admin/Event/SendTestInscriptionEmailAction.php
  sources/AppBundle/Event/Form/EventCFPTextType.php
  sources/AppBundle/Event/Form/EventType.php
  sources/AppBundle/Event/Model/Event.php
  sources/AppBundle/Event/Model/EventCoupon.php
  sources/AppBundle/Event/Model/Repository/EventCouponRepository.php
  sources/AppBundle/Event/Model/Repository/EventRepository.php
  templates/admin/event/add.html.twig
  templates/admin/event/edit.html.twig
  templates/admin/event/form.html.twig
  templates/admin/event/list.html.twig
  tests/behat/features/Admin/Events/GestionEvenements.feature
  tests/behat/features/Admin/Events/Inscriptions.feature
Labels: type:tech

#1682 Migration vers symfony de la partie personne morale
  app/config/config.yml
  app/config/routing/admin_members.yml
  app/config/security.yml
  app/config/services.yml
  htdocs/javascript/fonctions.js
  htdocs/pages/administration/cotisations.php
  htdocs/pages/administration/membre_personne_morale.php
  htdocs/pages/administration/personnes_morales.php
  htdocs/templates/administration/cotisations.html
  htdocs/templates/administration/forum_inscriptions.html
  htdocs/templates/administration/membre_coordonnees.html
  htdocs/templates/administration/membre_personne_morale.html
  htdocs/templates/administration/personnes_morales.html
  htdocs/templates/administration/personnes_physiques.html
  sources/Afup/Association/Cotisations.php
  sources/Afup/Association/Personnes_Morales.php
  sources/AppBundle/Association/Form/CompanyEditType.php
  sources/AppBundle/Association/Form/UserEditType.php
  sources/AppBundle/Association/Model/CompanyMember.php
  sources/AppBundle/Association/Model/Repository/CompanyMemberRepository.php
  sources/AppBundle/Association/Model/Repository/UserRepository.php
  sources/AppBundle/Association/UserMembership/StatisticsComputer.php
  sources/AppBundle/Controller/Admin/Members/CompanyAction.php
  sources/AppBundle/Controller/Admin/Members/CompanyDeleteAction.php
  sources/AppBundle/Controller/Admin/Members/CompanyListAction.php
  sources/AppBundle/Controller/Website/MemberShipController.php
  templates/admin/event/form.html.twig
  templates/admin/members/company/add.html.twig
  templates/admin/members/company/edit.html.twig
  templates/admin/members/company/form.html.twig
  templates/admin/members/company_list.html.twig
  templates/admin/members/user_edit.html.twig
  templates/admin/members/user_list.html.twig
  tests/behat/features/Admin/AccessCheckMembers.feature
  tests/behat/features/Admin/AdminPersonnesMorales.feature
  tests/behat/features/Admin/AdminPersonnesMoralesCotisations.feature
  tests/behat/features/Admin/AdminPersonnesPhysiques.feature
Labels: type:tech

#1688 #1680 ajout des listes des actualités dans le sitemap
  app/config/services.yml
  composer.json
  composer.lock
  db/seeds/Articles.php
  phinx.php
  sources/AppBundle/Controller/Website/NewsController.php
  sources/AppBundle/Subscriber/SitemapXmlSubscriber.php
  templates/site/news/list.html.twig
  templates/site/pager.html.twig
  tests/behat/features/Admin/Site/AdminSiteArticles.feature
Labels: type:tech, seo

#1685 Refactor de l'indexation de planete PHP
  .github/workflows/ci.yml
  Makefile
  app/config/services.yml
  clevercloud/cron.json
  composer.json
  composer.lock
  dependencies/magpierss/extlib/Snoopy.class.inc
  dependencies/magpierss/rss_cache.inc
  dependencies/magpierss/rss_fetch.inc
  dependencies/magpierss/rss_parse.inc
  dependencies/magpierss/rss_utils.inc
  doc/dev-setup.md
  htdocs/robots/planete/explorateur.php
  htdocs/templates/planete/images/cron.php
  phpstan.neon
  phpunit.xml
  sources/AppBundle/Clock/NativeClock.php
  sources/AppBundle/Command/PlaneteCrawlFeeds.php
  sources/PlanetePHP/CrawlingResult.php
  sources/PlanetePHP/DisplayableFeedArticle.php
  sources/PlanetePHP/FeedArticleRepository.php
  sources/PlanetePHP/FeedCrawler.php
  sources/PlanetePHP/SymfonyFeedClient.php
  tests/behat/bootstrap/FeatureContext.php
  tests/integration/PlanetePHP/FeedCrawlerTest.php
  tests/integration/fixtures/feed-atom.xml
  tests/integration/fixtures/feed-html.html
  tests/integration/fixtures/feed-rss.xml
  tests/support/DatabaseManager.php
  tests/support/IntegrationTestCase.php
  tests/support/MockClock.php
Labels: type:tech

#1655 Système de post automatique sur Bluesky
  .env.dist
  app/config/packages/http_client.yaml
  app/config/services.yml
  clevercloud/cron.json
  composer.json
  composer.lock
  db/migrations/20250228163339_create_video_notifier_history_table.php
  doc/dev-setup.md
  sources/AppBundle/Command/VideoNotifierCommand.php
  sources/AppBundle/Event/Model/Repository/PlanningRepository.php
  sources/AppBundle/Event/Model/Repository/SpeakerRepository.php
  sources/AppBundle/Event/Model/Repository/TalkRepository.php
  sources/AppBundle/Event/Model/Speaker.php
  sources/AppBundle/SocialNetwork/Bluesky/BlueskyPolyfill.php
  sources/AppBundle/SocialNetwork/Bluesky/BlueskyTransport.php
  sources/AppBundle/SocialNetwork/Bluesky/Session.php
  sources/AppBundle/SocialNetwork/Embed.php
  sources/AppBundle/SocialNetwork/SocialNetwork.php
  sources/AppBundle/SocialNetwork/Status.php
  sources/AppBundle/SocialNetwork/StatusId.php
  sources/AppBundle/SocialNetwork/Transport.php
  sources/AppBundle/VideoNotifier/Engine.php
  sources/AppBundle/VideoNotifier/HistoryEntry.php
  sources/AppBundle/VideoNotifier/HistoryRepository.php
  sources/AppBundle/VideoNotifier/StatusGenerator.php
  tests/unit/AppBundle/SocialNetwork/SocialNetworkTest.php
  tests/unit/AppBundle/TestCase.php
  tests/unit/AppBundle/VideoNotifier/StatusGeneratorTest.php
Labels: type: enhancement

#1697 #1695 Mise à jour du Geocoder
  app/config/config_test.yml
  app/config/services.yml
  composer.json
  composer.lock
  docker/dockerfiles/apachephp/Dockerfile
  sources/AppBundle/Offices/OfficeFinder.php
Labels: type:tech

#1701 Changement de la timezone pour MySQL
  .env.dist
Labels: type:tech
