Repository afup/web, pull requests merged in 2025-01, with the labels that each got.

#1591 Suppression des URLs Work Adventure
  app/Resources/views/site/offices.html.twig
  sources/AppBundle/Offices/OfficesCollection.php
Labels: type:tech

#1590 Rector installation
  .gitignore
  app/config/config.php
  composer.json
  composer.lock
  db/seeds/Session.php
  htdocs/pages/administration/compta_balance.php
  htdocs/pages/administration/compta_banque.php
  htdocs/pages/administration/compta_bilan.php
  htdocs/pages/administration/compta_conf_categorie.php
  htdocs/pages/administration/compta_conf_compte.php
  htdocs/pages/administration/compta_conf_evenement.php
  htdocs/pages/administration/compta_conf_operation.php
  htdocs/pages/administration/compta_conf_regle.php
  htdocs/pages/administration/compta_conf_reglement.php
  htdocs/pages/administration/compta_devis.php
  htdocs/pages/administration/compta_facture.php
  htdocs/pages/administration/compta_journal.php
  htdocs/pages/administration/compta_recherche.php
  htdocs/pages/administration/compta_synthese.php
  htdocs/pages/administration/cotisations.php
  htdocs/pages/administration/forum_facturation.php
  htdocs/pages/administration/forum_inscriptions.php
  htdocs/pages/administration/forum_joind_in.php
  htdocs/pages/administration/forum_partenaire.php
  htdocs/pages/administration/forum_planning.php
  htdocs/pages/administration/forum_sessions.php
  htdocs/pages/administration/index.php
  htdocs/pages/administration/membre_personne_morale.php
  htdocs/pages/administration/paybox_annule.php
  htdocs/pages/administration/paybox_effectue.php
  htdocs/pages/administration/paybox_erreur.php
  htdocs/pages/administration/paybox_refuse.php
  htdocs/pages/administration/personnes_morales.php
  htdocs/pages/administration/site_articles.php
  htdocs/pages/administration/site_feuilles.php
  htdocs/pages/event-payment/index.php
  htdocs/pages/event-payment/paybox_annule.php
  htdocs/pages/event-payment/paybox_effectue.php
  htdocs/pages/event-payment/paybox_erreur.php
  htdocs/pages/event-payment/paybox_refuse.php
  htdocs/pages/paiement/index.php
  htdocs/pages/paiement/paybox_annule.php
  htdocs/pages/paiement/paybox_effectue.php
  htdocs/pages/paiement/paybox_erreur.php
  htdocs/pages/paiement/paybox_refuse.php
  htdocs/pages/paiement/payment_tracking.php
  htdocs/templates/planete/images/cron.php
  rector.php
  sources/AppBundle/Controller/SiteBaseController.php
  sources/AppBundle/Event/Form/SpeakerType.php
  sources/AppBundle/Security/MyGithubAuthenticator.php
  sources/AppBundle/Security/TestGithubAuthenticator.php
Labels: type:tech

#1594 Ajout d'un `robots.txt` pour les IA génératives
  htdocs/robots.txt
Labels: category:infra, type:tech

#1601 Ajout de BlueSky sur les profils Speaker
  app/Resources/views/admin/speaker/add.html.twig
  app/Resources/views/admin/speaker/edit.html.twig
  app/Resources/views/blog/speakers.html.twig
  db/migrations/20250127123553_speaker_bluesky.php
  db/seeds/Conferenciers.php
  sources/AppBundle/Controller/Admin/Speaker/SpeakerAddAction.php
  sources/AppBundle/Controller/Admin/Speaker/SpeakerEditAction.php
  sources/AppBundle/Event/Form/SpeakerFormData.php
  sources/AppBundle/Event/Form/SpeakerFormDataFactory.php
  sources/AppBundle/Event/Form/SpeakerType.php
  sources/AppBundle/Event/Model/Repository/SpeakerRepository.php
  sources/AppBundle/Event/Model/Speaker.php
Labels: type: feature request
