Repository afup/web, pull requests merged in 2025-02, with the labels that each got.

#1605 On enlève SiteBaseController et tout ce qui va avec
  app/config/services.yml
  htdocs/app.php
  phpstan.neon
  sources/AppBundle/Controller/Admin/LoginAction.php
  sources/AppBundle/Controller/Admin/LostPasswordAction.php
  sources/AppBundle/Controller/Website/BlocksHandler.php
  sources/AppBundle/Controller/Website/CmsPageController.php
  sources/AppBundle/Controller/Website/CompanyPublicProfileController.php
  sources/AppBundle/Controller/Website/CompanyPublicProfileListController.php
  sources/AppBundle/Controller/Website/HomeController.php
  sources/AppBundle/Controller/Website/HtmlSitemapController.php
  sources/AppBundle/Controller/Website/MeetupsController.php
  sources/AppBundle/Controller/Website/Member/CompanyController.php
  sources/AppBundle/Controller/Website/Member/CompanyPublicProfileController.php
  sources/AppBundle/Controller/Website/Member/MembersController.php
  sources/AppBundle/Controller/Website/MemberController.php
  sources/AppBundle/Controller/Website/MemberShipController.php
  sources/AppBundle/Controller/Website/NewsController.php
  sources/AppBundle/Controller/Website/NewsletterController.php
  sources/AppBundle/Controller/Website/PayboxRedirectController.php
  sources/AppBundle/Controller/Website/SiteBaseController.php
  sources/AppBundle/Controller/Website/SiteControllerInterface.php
  sources/AppBundle/Controller/Website/StaticController.php
  sources/AppBundle/Controller/Website/TalksController.php
  sources/AppBundle/Controller/Website/TechletterController.php
  sources/AppBundle/Controller/Website/TechnoWatchController.php
  sources/AppBundle/Listener/LegacySiteListener.php
  sources/AppBundle/Twig/ViewRenderer.php
Labels: type:tech

#1610 Temps de session de 24 heures
  app/config/config.yml
Labels: type: enhancement

#1611 Corrige la modification de la programmation d'un session
  sources/Afup/Forum/AppelConferencier.php
  tests/behat/features/Admin/Events/Planning.feature
Labels: type: bug

#1617 Ajout de targets pour lancer PHP CS Fixer en local
  Makefile
Labels: type:tech

#1612 Ajout de la configuration de la timezone pour MySQL
  app/config/config.php
  app/config/config.yml
  sources/Afup/Corporate/_Site_Base_De_Donnees.php
  sources/Afup/Utils/Base_De_Donnees.php
  sources/AppBundle/AppBundle.php
Labels: type: bug

#1621 Corrections suite à la PR #1609
  sources/Afup/Association/Cotisations.php
  sources/Afup/Corporate/Article.php
  sources/PlanetePHP/FeedCrawler.php
Labels: type: bug

#1622 Gestion de l'absence de racine
  sources/Afup/Corporate/Branche.php
Labels: type: bug, priority: high

#1613 Corrige la modification de la programmation d'un session joindin
  sources/Afup/Forum/AppelConferencier.php
  tests/behat/features/Admin/Events/Planning.feature
Labels: type: bug

#1624 Pagination factures
  htdocs/pages/administration/compta_facture.php
  htdocs/templates/administration/compta_facture.html
  sources/Afup/Comptabilite/Facture.php
  sources/Afup/Forum/AppelConferencier.php
  tests/behat/features/Admin/Tresorerie/DevisFactures.feature
Labels: type: bug, priority: high

#1623 Mise à jour de l'encoding de la table `afup_planete_billet`
  db/migrations/20250210180403_planete_billet_encoding.php
Labels: type: bug, priority: low

#1627 Change le namespace de Twig
  rector.php
  sources/Afup/Utils/Mail.php
  sources/AppBundle/Controller/Event/CFP/EditAction.php
  sources/AppBundle/Controller/Event/CFP/IndexAction.php
  sources/AppBundle/Controller/Event/CFP/ProposeAction.php
  sources/AppBundle/Controller/Event/CFP/SidebarRenderer.php
  sources/AppBundle/Controller/Event/CFP/SpeakerAction.php
  sources/AppBundle/Controller/Website/MemberController.php
  sources/AppBundle/Email/Mailer/Mailer.php
  sources/AppBundle/Offices/OfficeFinder.php
  sources/AppBundle/Twig/AssetsExtension.php
  sources/AppBundle/Twig/OfficesExtension.php
Labels: type: enhancement, type:tech

#1628 Deprecated isSubmitted() before isValid()
  sources/AppBundle/Controller/Admin/Members/GeneralMeeting/ReportsAction.php
  sources/AppBundle/Controller/Admin/Planete/FeedEditAction.php
  sources/AppBundle/Controller/Admin/TechLetter/TechLetterGenerateController.php
  sources/AppBundle/Controller/Event/SpeakerSuggestionController.php
  sources/AppBundle/Controller/Website/Member/CompanyPublicProfileController.php
  sources/AppBundle/Event/Speaker/SpeakerPage.php
Labels: type: enhancement, type:tech

#1593 Refactor de la liste des antennes en DTOs
  app/Resources/views/admin/members/user_list.html.twig
  app/Resources/views/site/company_public_profile.html.twig
  app/Resources/views/site/offices.html.twig
  app/Resources/views/site/talks/list.html.twig
  app/config/services.yml
  sources/AppBundle/Antennes/Antenne.php
  sources/AppBundle/Antennes/AntennesCollection.php
  sources/AppBundle/Antennes/City.php
  sources/AppBundle/Antennes/Map.php
  sources/AppBundle/Antennes/Meetup.php
  sources/AppBundle/Antennes/Point.php
  sources/AppBundle/Antennes/Position.php
  sources/AppBundle/Antennes/Socials.php
  sources/AppBundle/Association/Form/CompanyPublicProfile.php
  sources/AppBundle/Association/Form/ContactDetailsType.php
  sources/AppBundle/Association/Form/NearestOfficeChoiceType.php
  sources/AppBundle/Association/Model/User.php
  sources/AppBundle/Controller/Admin/Members/UserListAction.php
  sources/AppBundle/Controller/Website/CompanyPublicProfileController.php
  sources/AppBundle/Controller/Website/StaticController.php
  sources/AppBundle/Controller/Website/TalksController.php
  sources/AppBundle/Event/Form/TicketType.php
  sources/AppBundle/Indexation/Meetups/MeetupScraper.php
  sources/AppBundle/Indexation/Meetups/Runner.php
  sources/AppBundle/Indexation/Meetups/Transformer.php
  sources/AppBundle/Offices/OfficeFinder.php
  sources/AppBundle/Offices/OfficesCollection.php
  sources/AppBundle/Twig/OfficesExtension.php
  tests/units/AppBundle/Indexation/Meetups/MeetupScrapper.php
  tests/units/AppBundle/Indexation/Meetups/Transformer.php
Labels: type:tech

#1630 Upgrade AlgoliaSearch
  app/config/services.yml
  composer.json
  composer.lock
  sources/AppBundle/Command/IndexMeetupsCommand.php
  sources/AppBundle/Controller/Website/HomeController.php
  sources/AppBundle/Indexation/Meetups/Runner.php
  sources/AppBundle/Indexation/Talks/Runner.php
Labels: type:tech

#1633 Correction du type pour les IDs
  htdocs/pages/administration/compta_journal.php
  sources/Afup/Comptabilite/Comptabilite.php
Labels: type: bug, priority: high

#1631 Suppression des dépréciations
  app/Resources/views/event/ticket/ticket.html.twig
  app/Resources/views/site/secondary_menu.html.twig
  composer.json
  composer.lock
  sources/AppBundle/Association/Form/CompanyPublicProfile.php
  sources/AppBundle/Event/Speaker/SpeakerPage.php
  sources/AppBundle/Planete/FeedFormData.php
  sources/AppBundle/Security/TestGithubAuthenticator.php
  sources/AppBundle/SpeakerInfos/Form/HotelReservationType.php
Labels: type:tech

#1632 Upgrade Smarty 5.4
  composer.json
  composer.lock
  htdocs/templates/administration/compta_balance.html
  htdocs/templates/administration/compta_banque.html
  htdocs/templates/administration/compta_bilan.html
  htdocs/templates/administration/compta_journal.html
  htdocs/templates/administration/forum_facturation.html
  htdocs/templates/administration/forum_inscriptions.html
  htdocs/templates/administration/forum_sessions.html
  htdocs/templates/administration/personnes_morales.html
  htdocs/templates/administration/site_articles.html
  sources/Afup/Bootstrap/Http.php
  sources/AppBundle/Controller/LegacyController.php
Labels: type:tech

#1636 Suppression du cache des tests
  .github/workflows/ci.yml
Labels: type:tech

#1637 Amélioration de la clé de cache Docker
  .github/workflows/ci.yml
Labels: priority: low, type:tech

#1639 Suppression des dépréciations pour les Command
  app/config/services.yml
  sources/AppBundle/Command/CfpNotificationCommand.php
  sources/AppBundle/Command/CleanThrottlingCommand.php
  sources/AppBundle/Command/DevCallBackPayboxCotisationCommand.php
  sources/AppBundle/Command/GeneralMeetupNotificationCommand.php
  sources/AppBundle/Command/IndexMeetupsCommand.php
  sources/AppBundle/Command/IndexTalksCommand.php
  sources/AppBundle/Command/QrCodesGeneratorCommand.php
  sources/AppBundle/Command/RegistrationsExporterCommand.php
  sources/AppBundle/Command/ScrappingMeetupEventsCommand.php
  sources/AppBundle/Command/SlackMemberNotificationCommand.php
  sources/AppBundle/Command/SubscriptionReminderCommand.php
  sources/AppBundle/Command/SynchMembersCommand.php
  sources/AppBundle/Command/SynchTechLetterCommand.php
  sources/AppBundle/Command/TicketStatsNotificationCommand.php
  sources/AppBundle/Command/TwitterBotCommand.php
  sources/AppBundle/Command/UpdateCompanyMemberStateCommand.php
  sources/AppBundle/Command/UpdateMailchimpMembersCommand.php
  sources/AppBundle/Command/UpdateUserStateCommand.php
  sources/AppBundle/Command/VideosDataCommand.php
  sources/AppBundle/Slack/Field.php
Labels: type:tech

#1640 On corrige quelques bugs divers
  .env.dist
  app/config/services.yml
  sources/AppBundle/Command/SynchMembersCommand.php
  sources/AppBundle/Controller/Legacy/Forum2016SessionsAction.php
  sources/AppBundle/Mailchimp/MailchimpMembersAutoListSynchronizer.php
  sources/AppBundle/TechLetter/MailchimpSynchronizer.php
Labels: type: bug

#1641 Correction du typage pour mktime
  htdocs/pages/administration/forum_planning.php
Labels: type: bug

#1642 MIse à jour de Node.js
  Makefile
  clevercloud/scripts/cc_pre_build_hook.sh
  docker/dockerfiles/apachephp/Dockerfile
  htdocs/npm-shrinkwrap.json
  htdocs/package.json
  htdocs/templates/site/scss/components/prev-next-links.scss
  htdocs/templates/site/scss/styles.scss
  package-lock.json
  package.json
  yarn.lock
Labels: type:tech

#1643 Optimisation du temps des tests fonctionnels
  composer.json
  composer.lock
  tests/behat/bootstrap/FeatureContext.php
Labels: type: enhancement, type:tech

#1635 Mise à jour de l'encoding des tables
  db/migrations/20250218154548_update_tables_engine_to_inno_db.php
  db/migrations/20250218154608_update_tables_encoding.php
  docker/dockerfiles/mysql/my.cnf
  docker/dockerfiles/mysqltest/my.cnf
  sources/Afup/Bootstrap/Http.php
  sources/Afup/Forum/Inscriptions.php
  sources/Afup/Utils/Logs.php
Labels: type:tech

#1634 Upgrade Symfony 4.4
  .gitignore
  app/AppKernel.php
  composer.json
  composer.lock
  sources/AppBundle/Association/CompanyMembership/UserCompany.php
  sources/AppBundle/Association/Event/NewMemberEvent.php
  sources/AppBundle/Association/Event/UserDisabledEvent.php
  sources/AppBundle/CFP/SpeakerFactory.php
  sources/AppBundle/Controller/Website/MemberShipController.php
  tests/behat/features/Admin/AdminPersonnesPhysiquesCotisations.feature
  tests/behat/features/Admin/Events/Conferences.feature
  tests/behat/features/Admin/Events/Inscriptions.feature
  tests/behat/features/MembersArea/Index.feature
Labels: type:tech

#1644 Optimisations pour la google search console video
  app/Resources/views/event/calendar.html.twig
  app/Resources/views/site/become_member.html.twig
  app/Resources/views/site/home.html.twig
  app/Resources/views/site/talks/show.html.twig
  db/seeds/Session.php
Labels: type:tech, seo

#1649 Documentation Docker pour les ARM
  README.md
Labels: type: documentation

#1650 Désactivation des polyfills inutiles
  composer.json
  composer.lock
Labels: priority: low, type:tech

#1651 Add functionnal tests
  .env.dist
  tests/behat/features/Admin/Site/AdminSiteArticles.feature
  tests/behat/features/PublicSite/SuperApero.feature
  tests/behat/files/super_apero.csv
Labels: type:tech

#1652 Simplification du docker compose
  Makefile
  compose.yml
  docker/bin/bash
Labels: type:tech
