Repository afup/web, pull requests merged in 2025-04, with the labels that each got.

#1704 #1681 ajout de pages dans le sitemap
  app/config/routing.yml
  sources/AppBundle/Controller/Website/TalksController.php
  sources/AppBundle/Subscriber/SitemapXmlSubscriber.php
  templates/site/talks/list.html.twig
Labels: type:tech, seo

#1706 Nettoyage de la config des services de Planete PHP
  app/config/services.yml
Labels: type:tech

#1710 Simplification de la config des services
  app/config/services.yml
Labels: type:tech

#1713 Nettoyage de la config des services
  app/AppKernel.php
  app/config/services.yml
  sources/AppBundle/DependencyInjection/TingRepositoryPass.php
Labels: type:tech

#1712 MySQL on supprime la gestion de la timezone
  .env.dist
  app/config/config.yml
  compose.yml
  docker/dockerfiles/mysql/my.cnf
  docker/dockerfiles/mysqltest/my.cnf
  sources/Afup/Utils/Base_De_Donnees.php
Labels: type:tech

#1715 Groupement des évènements par années
  sources/AppBundle/Event/Form/EventCompareSelectType.php
  sources/AppBundle/Event/Form/EventSelectType.php
  sources/AppBundle/Event/Form/Support/EventHelper.php
  tests/unit/AppBundle/Event/Form/Support/EventHelperTest.php
Labels: type: enhancement

#1718 On supprime des dépréciations
  app/config/services.yml
  composer.json
  composer.lock
  htdocs/app.php
  htdocs/templates/administration/compta_banque.html
  htdocs/templates/administration/compta_conf_evenement.html
  templates/site/base.html.twig
Labels: type:tech

#1719 On corrige le x-forwarded pour la génération des liens en https
  htdocs/app.php
Labels: type: bug, priority: critical

#1714 #1695 upgrade oauth2-client-bundle
  composer.json
  composer.lock
  sources/AppBundle/Controller/GithubController.php
  sources/AppBundle/Event/Model/GithubUser.php
  sources/AppBundle/Event/Model/Repository/GithubUserRepository.php
  sources/AppBundle/Security/MyGithubAuthenticator.php
Labels: type:tech

#1720 Archivage des évènements
  app/config/routing/admin_event.yml
  db/migrations/20250412223717_add_archived_at_to_events.php
  htdocs/pages/administration/forum_inscriptions.php
  sources/Afup/Forum/Forum.php
  sources/AppBundle/Controller/Admin/Event/ArchiveAction.php
  sources/AppBundle/Controller/Admin/Event/RestoreAction.php
  sources/AppBundle/Event/Form/EventSelectType.php
  sources/AppBundle/Event/Model/Event.php
  sources/AppBundle/Event/Model/Repository/EventRepository.php
  templates/admin/event/edit.html.twig
  templates/admin/event/list.html.twig
Labels: type: enhancement

#1721 Amélioration de la performance de la liste des events
  sources/AppBundle/Controller/Admin/Event/RemoveEventAction.php
  sources/AppBundle/Event/Model/Repository/EventRepository.php
  templates/admin/event/list.html.twig
Labels: type: enhancement

#1722 Mise à jour de l'authentification
  app/config/config.yml
  app/config/security.yml
  app/config/services.yml
  db/migrations/20250412110752_user_password.php
  sources/AppBundle/Association/Model/Repository/UserRepository.php
  sources/AppBundle/Association/Model/User.php
  sources/AppBundle/Association/UserMembership/UserService.php
  sources/AppBundle/Controller/Admin/Members/UserAddAction.php
  sources/AppBundle/Controller/Admin/Members/UserEditAction.php
  sources/AppBundle/Controller/Website/MemberShipController.php
  sources/AppBundle/Event/Form/SpeakerType.php
  sources/AppBundle/Event/Model/GithubUser.php
  sources/AppBundle/Event/Model/Repository/GithubUserRepository.php
  sources/AppBundle/Security/GithubAuthenticator.php
  sources/AppBundle/Security/LegacyAuthenticator.php
  sources/AppBundle/Security/LegacyHashAuthenticator.php
  sources/AppBundle/Security/LegacyHasher.php
  sources/AppBundle/Security/TestGithubAuthenticator.php
  sources/AppBundle/Slack/UsersChecker.php
  templates/admin/login.html.twig
Labels: type:tech

#1724 Suppression d'une surcharge de type inutile
  sources/AppBundle/Controller/Event/TicketController.php
Labels: type:tech

#1723 Correction du type de retour
  sources/AppBundle/Event/Model/Repository/TalkRepository.php
Labels: type:tech

#1726 On supprime des dépréciations
  app/config/config.yml
  app/config/routing/global.yml
  app/config/services.yml
  htdocs/pages/administration/cotisations.php
  htdocs/pages/administration/forum_facturation.php
  htdocs/pages/administration/forum_inscriptions.php
  htdocs/pages/administration/forum_sessions.php
  htdocs/pages/administration/membre_administrateur.php
  htdocs/pages/administration/site_articles.php
  sources/AppBundle/Association/Model/Repository/UserRepository.php
  sources/AppBundle/Association/Model/User.php
  sources/AppBundle/Controller/LegacyController.php
  sources/AppBundle/Event/Model/Talk.php
  sources/AppBundle/Security/TalkVoter.php
  sources/AppBundle/VideoNotifier/StatusGenerator.php
Labels: type:tech

#1728 Passage au niveau 3 de PHPStan
  phpstan.neon
  sources/AppBundle/Controller/Admin/Members/UserEditAction.php
  sources/AppBundle/Controller/Website/MemberShipController.php
  sources/AppBundle/Email/Mailer/Adapter/PhpMailerAdapter.php
  sources/AppBundle/Event/Form/SpeakerFormData.php
  sources/AppBundle/Event/Speaker/SpeakerPage.php
  sources/AppBundle/Validator/Constraints/UniqueEntity.php
Labels: type:tech

#1731 Test du générateur de tech letter
  tests/unit/AppBundle/TechLetter/Model/TechLetterFactoryTest.php
  tests/unit/AppBundle/TechLetter/Model/fixtures/empty.json
  tests/unit/AppBundle/TechLetter/Model/fixtures/full.json
  tests/unit/AppBundle/TechLetter/Model/fixtures/keys-present-but-empty-values.json
  tests/unit/AppBundle/TechLetter/Model/fixtures/with-only-articles.json
  tests/unit/AppBundle/TechLetter/Model/fixtures/with-only-first-news.json
  tests/unit/AppBundle/TechLetter/Model/fixtures/with-only-projects.json
  tests/unit/AppBundle/TechLetter/Model/fixtures/with-only-second-news.json
Labels: type:tech

#1735 Suppression de tests inutiles
  sources/AppBundle/SocialNetwork/Bluesky/BlueskyTransport.php
Labels: type:tech

#1733 Ajout de types natifs à la tech letter
  sources/AppBundle/TechLetter/Model/Article.php
  sources/AppBundle/TechLetter/Model/News.php
  sources/AppBundle/TechLetter/Model/Project.php
  sources/AppBundle/TechLetter/Model/TechLetter.php
  tests/unit/AppBundle/TechLetter/Model/TechLetterFactoryTest.php
Labels: type:tech

#1736 Ajout de types natifs à l'entité `Vote`
  sources/AppBundle/Event/Model/Vote.php
Labels: type:tech

#1732 Utilisation de l'éditeur plus récent sur les events
  sources/AppBundle/Event/Form/EventCFPTextType.php
  templates/admin/event/form.html.twig
Labels: type: enhancement

#1740 Activation du scroll horizontal quand la fenêtre est trop petite
  templates/admin/base_with_header.html.twig
Labels: type: enhancement

#1738 Mise à jour de PHP CS Fixer
  .gitignore
  .php-cs-fixer.php
  composer.json
  composer.lock
  htdocs/pages/administration/compta_journal.php
  sources/Afup/Forum/Forum.php
Labels: type:tech

#1741 Correction de quelques types / erreurs
  htdocs/pages/administration/forum_inscriptions.php
  htdocs/pages/administration/site_feuilles.php
  htdocs/templates/administration/cotisations.html
  htdocs/templates/administration/forum_inscriptions.html
  sources/Afup/Association/Cotisations.php
  sources/Afup/Comptabilite/Facture.php
  sources/Afup/Forum/Facturation.php
  sources/Afup/Forum/Inscriptions.php
  sources/AppBundle/Association/Model/CompanyMember.php
  sources/AppBundle/Association/UserMembership/SeniorityComputer.php
  sources/AppBundle/Controller/Admin/Members/GeneralMeeting/ListAction.php
  sources/AppBundle/Controller/Admin/Members/GeneralMeeting/ListingAction.php
  sources/AppBundle/Controller/Website/MemberController.php
  sources/AppBundle/Controller/Website/MemberShipController.php
  sources/AppBundle/Event/Form/Support/EventHelper.php
  sources/AppBundle/Event/Model/GithubUser.php
  sources/AppBundle/Event/Model/Lead.php
  sources/AppBundle/GeneralMeeting/GeneralMeetingRepository.php
  sources/AppBundle/TechLetter/Model/TechLetterFactory.php
Labels: type:tech

#1744 On passe à tFPDF pour l'UTF-8
  Makefile
  assets/fonts/Arial.ttf
  assets/fonts/Arial_Bold.ttf
  assets/fonts/Arial_Bold_Italic.ttf
  assets/fonts/Arial_Italic.ttf
  composer.json
  composer.lock
  sources/Afup/Association/Cotisations.php
  sources/Afup/Comptabilite/Facture.php
  sources/Afup/Comptabilite/PDF.php
  sources/Afup/Forum/Facturation.php
  sources/Afup/Utils/PDF_AG.php
  sources/Afup/Utils/PDF_Facture.php
  sources/AppBundle/Controller/Admin/Members/GeneralMeeting/ListingAction.php
  tests/behat/features/Admin/Events/FacturesEvennement.feature
  tests/behat/features/Admin/Tresorerie/DevisFactures.feature
  tests/behat/features/MembersArea/Index.feature
Labels: type:tech

#1749 Le `$name` d'un utilisateur GitHub est nullable en base
  sources/AppBundle/Event/Model/GithubUser.php
Labels: type: bug

#1750 Corrections PHPStan
  sources/AppBundle/Controller/Admin/Speaker/SpeakerRegisterAction.php
  sources/AppBundle/Event/Model/Repository/SpeakerRepository.php
  sources/AppBundle/Event/Model/Repository/TicketRepository.php
  sources/AppBundle/Event/Validator/Constraints/CorporateMemberValidator.php
  sources/AppBundle/SpeakerInfos/Form/HotelReservationType.php
Labels: type: enhancement

#1752 Corrige la notification au trésorier
  sources/Afup/Association/Cotisations.php
  sources/AppBundle/Controller/Website/MemberShipController.php
Labels: type: bug
