Repository afup/web, pull requests merged in 2025-05, with the labels that each got.

#1737 Upgrade PHP 8.2
  .github/workflows/ci.yml
  composer.json
  composer.lock
  docker/dockerfiles/apachephp/Dockerfile
  patches/ccmbenchmark-ting-bundle-src-tingbundle-datacollector-tingcachedatacollector-php.patch
  patches/ccmbenchmark-ting-bundle-src-tingbundle-datacollector-tingdriverdatacollector-php.patch
  patches/setasign-tfpdf-tfpdf-php.patch
  patches/znk3r-html-quickform-html-quickform-date-php.patch
  patches/znk3r-html-quickform-html-quickform-php.patch
  phpstan.neon
Labels: type:tech

#1753 Tarif spécial forum : fixture + test
  db/seeds/Tarif.php
  tests/behat/features/Admin/Events/TokensVIsiteurs.feature
Labels: type: enhancement

#1754 Création des évènements avec tarifs HT par défaut
  sources/AppBundle/Event/Model/Event.php
Labels: type: enhancement

#1755 Réduction de la largeur du menu de l'admin
  templates/admin/base_with_header.html.twig
Labels: type: enhancement

#1758 Migration des DTOs des antennes en PHP 8
  sources/AppBundle/Antennes/Antenne.php
  sources/AppBundle/Antennes/AntennesCollection.php
  sources/AppBundle/Antennes/City.php
  sources/AppBundle/Antennes/LegendAttachment.php
  sources/AppBundle/Antennes/Map.php
  sources/AppBundle/Antennes/Meetup.php
  sources/AppBundle/Antennes/Point.php
  sources/AppBundle/Antennes/Position.php
  sources/AppBundle/Antennes/Socials.php
  templates/site/offices.html.twig
Labels: type:tech

#1759 Migration de l'enum `SocialNetwork` en natif
  composer.json
  composer.lock
  sources/AppBundle/SocialNetwork/Bluesky/BlueskyTransport.php
  sources/AppBundle/SocialNetwork/SocialNetwork.php
  sources/AppBundle/VideoNotifier/Engine.php
  sources/AppBundle/VideoNotifier/StatusGenerator.php
  tests/unit/AppBundle/SocialNetwork/SocialNetworkTest.php
  tests/unit/AppBundle/VideoNotifier/StatusGeneratorTest.php
Labels: type:tech

#1765 Optimisations pour la google search console video
  sources/AppBundle/Controller/Website/TalksController.php
  templates/site/talks/list.html.twig
Labels: seo

#1762 Modernisation des extensions Twig
  app/config/services.yml
  sources/AppBundle/Twig/AssetsExtension.php
  sources/AppBundle/Twig/OfficesExtension.php
  sources/AppBundle/Twig/TwigExtension.php
Labels: type:tech

#1771 On corrige l'image docker pour pouvoir utiliser du jpg avec GD
  docker/dockerfiles/apachephp/Dockerfile
  tests/behat/features/EventPages/Cfp.feature
  tests/behat/files/avatar1.jpg
Labels: type: enhancement

#1768 Ajout de la date de début du CFP
  db/migrations/20250520223757_add_date_debut_cfp.php
  db/seeds/Event.php
  sources/AppBundle/Controller/Event/CFP/EditAction.php
  sources/AppBundle/Controller/Event/CFP/ProposeAction.php
  sources/AppBundle/Event/Form/EventType.php
  sources/AppBundle/Event/Form/TalkType.php
  sources/AppBundle/Event/Model/Event.php
  sources/AppBundle/Event/Model/Repository/EventRepository.php
  sources/AppBundle/Event/Model/Talk.php
  sources/AppBundle/Event/Talk/TalkFormHandler.php
  templates/admin/event/form.html.twig
  templates/event/cfp/edit.html.twig
  templates/event/cfp/form.html.twig
  templates/event/cfp/home.html.twig
  templates/event/cfp/propose.html.twig
  templates/event/cfp/sidebar.html.twig
  tests/behat/features/Admin/Events/GestionEvenements.feature
  tests/behat/features/EventPages/Cfp.feature
  tests/unit/AppBundle/Event/Model/EventTest.php
  translations/messages.en.yml
  translations/messages.fr.yml
Labels: type: feature request

#1778 Correction du blocage de l'ouverture du CFP
  templates/event/cfp/propose.html.twig
Labels: type: bug

#1760 Upgrade de valinor en v1 suite au passage en PHP 8
  composer.json
  composer.lock
Labels: type:tech

#1779 Correction pour la date d'ouverture du CFP
  sources/AppBundle/Event/Model/Repository/EventRepository.php
Labels: type: bug

#1780 Correction de l'envoi de la cotisation par email
  sources/Afup/Association/Cotisations.php
  tests/behat/features/MembersArea/Index.feature
Labels: type: bug, priority: low

#1781 Correction d'une erreur de type du synchronizer mailchimp
  sources/AppBundle/TechLetter/MailchimpSynchronizer.php
Labels: type: bug, priority: low

#1761 Upgrade de doctrine/dbal en v4 suite au passage en PHP 8
  app/config/services.yml
  bin/doctrine-dbal
  composer.json
  composer.lock
  sources/AppBundle/Doctrine/ConnectionFactory.php
  sources/AppBundle/Event/Model/Repository/EventStatsRepository.php
  sources/AppBundle/GeneralMeeting/GeneralMeetingRepository.php
  sources/AppBundle/VideoNotifier/HistoryRepository.php
  sources/PlanetePHP/FeedArticleRepository.php
  sources/PlanetePHP/FeedRepository.php
Labels: type:tech

#1770 Mise à jour de PHPUnit en version 11
  composer.json
  composer.lock
  rector.php
  tests/support/IntegrationTestCase.php
  tests/unit/Afup/Association/CotisationsTest.php
  tests/unit/Afup/Utils/UtilsTest.php
  tests/unit/AppBundle/Association/MembershipFeeReferenceGeneratorTest.php
  tests/unit/AppBundle/Association/Model/CompanyMemberTest.php
  tests/unit/AppBundle/Compta/Importer/AutoQualifierTest.php
  tests/unit/AppBundle/Event/Form/Support/EventHelperTest.php
  tests/unit/AppBundle/Event/Model/EventTest.php
  tests/unit/AppBundle/Event/Model/SpeakerTest.php
  tests/unit/AppBundle/Indexation/Meetups/MeetupClientTest.php
  tests/unit/AppBundle/Payment/PayboxTest.php
  tests/unit/AppBundle/SocialNetwork/SocialNetworkTest.php
  tests/unit/AppBundle/Subtitles/ParserTest.php
  tests/unit/AppBundle/TechLetter/Model/TechLetterFactoryTest.php
  tests/unit/AppBundle/TestCase.php
  tests/unit/AppBundle/VideoNotifier/StatusGeneratorTest.php
Labels: type:tech

#1786 Utilisation de `ramsey/composer-install` dans la CI
  .github/workflows/ci.yml
Labels: type:tech

#1787 Fix synchonizer Mailchimp
  sources/AppBundle/Mailchimp/Mailchimp.php
  sources/AppBundle/TechLetter/MailchimpSynchronizer.php
Labels: type: bug, priority: low

#1788 Redirection vers les pages avec `id_forum`
  htdocs/pages/administration/forum_facturation.php
  htdocs/pages/administration/forum_inscriptions.php
  htdocs/pages/administration/forum_planning.php
  htdocs/pages/administration/forum_sessions.php
  sources/Afup/fonctions.php
Labels: type: enhancement

#1798 Mise à jour du hash du commit à ignorer suite au merge
  .git-blame-ignore-revs
Labels: priority: low, type:tech

#1797 Réorg du menu
  app/config/config.yml
  templates/admin/base_with_header.html.twig
  templates/admin/menu.html.twig
  tests/behat/features/Admin/Events/GestionEvenements.feature
  tests/behat/features/Admin/Events/Inscriptions.feature
  tests/behat/features/Admin/Members/GeneralMeeting/GeneralMeeting.feature
  tests/behat/features/Admin/Members/GeneralMeeting/GeneralMeetingQuestions.feature
  tests/behat/features/Admin/Members/GeneralMeeting/GeneralMeetingReports.feature
  tests/behat/features/Admin/Members/GeneralMeeting/GeneralMeetingVotes.feature
Labels: type: enhancement

#1799 Menu `Venue speakers` renommé en `Infos speakers`
  app/config/config.yml
  templates/admin/event/speakers_expenses.html.twig
  templates/admin/event/speakers_management.html.twig
  tests/behat/features/Admin/AdminInfosSpeakers.feature
Labels: type: enhancement

#1800 Correction de l'emplacement du controller des votes
  app/config/routing/event.yml
  sources/AppBundle/Controller/Event/VoteController.php
Labels: type: bug, priority: medium

#1801 Cast de l'id de talk en int
  sources/AppBundle/Controller/Event/VoteController.php
Labels: type: bug, priority: medium

#1802 Corrections pour le vote du CFP
  db/seeds/Session.php
  sources/AppBundle/Controller/Event/VoteController.php
  sources/AppBundle/Event/Model/Vote.php
  tests/behat/bootstrap/FeatureContext.php
  tests/behat/features/EventPages/Cfp.feature
Labels: type: bug, priority: medium

#1803 Refactor d'un array en DTO
  sources/AppBundle/Calendar/IcsPLanningGenerator.php
  sources/AppBundle/Calendar/JsonPlanningGenerator.php
  sources/AppBundle/Command/VideosDataCommand.php
  sources/AppBundle/Controller/Admin/Speaker/SpeakerRegisterAction.php
  sources/AppBundle/Controller/Event/BlogController.php
  sources/AppBundle/Event/JsonLd.php
  sources/AppBundle/Event/Model/Repository/TalkRepository.php
  sources/AppBundle/Event/Model/TalkAggregate.php
  sources/AppBundle/Event/Speaker/SpeakerPage.php
  sources/AppBundle/Openfeedback/OpenfeedbackJsonGenerator.php
  templates/blog/planning.html.twig
  templates/blog/program.html.twig
Labels: type:tech

#1807 Ajout du model du template generic des repositories
  sources/AppBundle/Association/Model/Repository/CompanyMemberInvitationRepository.php
  sources/AppBundle/Association/Model/Repository/GeneralMeetingQuestionRepository.php
  sources/AppBundle/Association/Model/Repository/GeneralMeetingResponseRepository.php
  sources/AppBundle/Association/Model/Repository/GeneralMeetingVoteRepository.php
  sources/AppBundle/Association/Model/Repository/SubscriptionReminderLogRepository.php
  sources/AppBundle/Association/Model/Repository/SubscriptionRepository.php
  sources/AppBundle/Association/Model/Repository/TechletterSubscriptionsRepository.php
  sources/AppBundle/Association/Model/Repository/TechletterUnsubscriptionsRepository.php
  sources/AppBundle/Controller/Admin/TechLetter/TechLetterGenerateController.php
  sources/AppBundle/Event/Model/Repository/BadgeRepository.php
  sources/AppBundle/Event/Model/Repository/EventCouponRepository.php
  sources/AppBundle/Event/Model/Repository/EventRepository.php
  sources/AppBundle/Event/Model/Repository/GithubUserRepository.php
  sources/AppBundle/Event/Model/Repository/InvoiceRepository.php
  sources/AppBundle/Event/Model/Repository/RoomRepository.php
  sources/AppBundle/Event/Model/Repository/SpeakerSuggestionRepository.php
  sources/AppBundle/Event/Model/Repository/SponsorScanRepository.php
  sources/AppBundle/Event/Model/Repository/SponsorTicketRepository.php
  sources/AppBundle/Event/Model/Repository/TalkInvitationRepository.php
  sources/AppBundle/Event/Model/Repository/TalkRepository.php
  sources/AppBundle/Event/Model/Repository/TalkToSpeakersRepository.php
  sources/AppBundle/Event/Model/Repository/TicketEventTypeRepository.php
  sources/AppBundle/Event/Model/Repository/TicketSpecialPriceRepository.php
  sources/AppBundle/Event/Model/Repository/TicketTypeRepository.php
  sources/AppBundle/Event/Model/Repository/UserBadgeRepository.php
  sources/AppBundle/Event/Model/Repository/VoteRepository.php
  sources/AppBundle/Security/ActionThrottling/LogRepository.php
  sources/AppBundle/Site/Model/Repository/ArticleRepository.php
  sources/AppBundle/Site/Model/Repository/RubriqueRepository.php
  sources/AppBundle/TechLetter/Model/Repository/SendingRepository.php
Labels: type:tech

#1809 Nettoyage des types
  sources/AppBundle/Controller/Event/TicketController.php
  sources/AppBundle/Security/ActionThrottling/ActionThrottling.php
  sources/AppBundle/Security/ActionThrottling/LogRepository.php
Labels: type:tech

#1810 Recherche des personnes morales insensible à la casse
  sources/AppBundle/Association/Model/Repository/CompanyMemberRepository.php
Labels: type: enhancement

#1813 Suppression d'une méthode non utilisée
  sources/AppBundle/Antennes/AntennesCollection.php
Labels: type:tech

#1812 Amélioration du typage
  sources/AppBundle/Controller/Admin/Members/GeneralMeeting/ListAction.php
  sources/AppBundle/Controller/Admin/Members/GeneralMeeting/ReportsAction.php
  sources/AppBundle/Controller/Admin/Members/GeneralMeetingQuestion/DeleteAction.php
  sources/AppBundle/Controller/Admin/Members/GeneralMeetingQuestion/EditAction.php
  sources/AppBundle/Controller/Admin/Members/GeneralMeetingVote/CloseAction.php
  sources/AppBundle/Controller/Admin/Members/GeneralMeetingVote/OpenAction.php
Labels: type:tech

#1818 Nettoyage de la config Rector
  rector.php
Labels: type:tech
